name: fada
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  geolocator: ^13.0.1


  # ðŸ”— HTTP pour les appels REST API
  http: ^1.2.2

  # ðŸ’¾ Stockage local pour l'ID utilisateur et les prÃ©fÃ©rences
  shared_preferences: ^2.3.2

  # ðŸ–¼ï¸ Pour la sÃ©lection et capture dâ€™images


  # ðŸŒ™ IcÃ´nes Cupertino (style iOS)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ðŸ§¹ Bonnes pratiques et rÃ¨gles de code
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ðŸ“ Ajoute ici tes images ou fichiers statiques si besoin :
  # assets:
  #   - assets/images/
  #   - assets/icons/
